### ISSUE TITLE
Append TOI: Connect Time Delay Algorithm

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/sdpi-fhir#103]
See also: https://confluence.hl7.org/display/GP/Topic%3A+Connect+Time+Delay+Algorithm

**Comment by ToddCooper** [comment]
@d-gregorczyk  Note also #33  ... should we nuke the earlier one or is this related?

**Comment by ToddCooper** [comment]
Update related [sdpi-supplement-issues.adoc](https://github.com/IHE/sdpi-fhir/blob/master/SDPi_Supplement/asciidoc/sdpi-supplement-issues.adoc)  item when complete, indicating where the updates were made or the branche(s) that captured the updates, as well as moving from OPEN to CLOSED lists if appropriate.
