### ISSUE TITLE
Append TOI: MDIB Report Retrofit / Best Practices

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/sdpi-fhir#104]
See also: https://confluence.hl7.org/pages/viewpage.action?pageId=104761310

**Comment by ToddCooper** [comment]
Update related [sdpi-supplement-issues.adoc](https://github.com/IHE/sdpi-fhir/blob/master/SDPi_Supplement/asciidoc/sdpi-supplement-issues.adoc)  item when complete, indicating where the updates were made or the branche(s) that captured the updates, as well as moving from OPEN to CLOSED lists if appropriate.

**Comment by ToddCooper** [comment]
@d-gregorczyk  -- Note:  This is still listed as OPEN in the [Topics of Interest Table entry](https://confluence.hl7.org/pages/viewpage.action?pageId=82912211#TopicsofInterest-TopicsontheTable), so it is included in the OPEN list in the SDPi Supplement Issues document.

**Comment by ToddCooper** [comment]
From the SDPi 1.0 Workshop:  For Vol 2 and Vol 3﻿

**Comment by JavierEspina** [comment]
Decided to add two additional requirements and one note:
REQ: (when using MDPWS binding) HTTP shall be used for everything that is not discovery (which uses UDP) - contingent on that requirement not being already buried into the underlying stds (in which case this would be a good)
REQ: (when using MDPWS binding) for every consumer subscription there SHALL be only one TCP connection at a time
Note: all introduced provider requirements (5ish) should ensure absence of version gaps or flips at the consumer side... and if a consumer experiences that something is really wrong and SHOULD reconnect or go into a fail-safe mode.

We MAY add a note in a general part of SDPi 1.0 that CONSUMER implementers are well advised to take a look at the PROVIDER requirements (to better comprehend what behavior to expect). This is common sense / practice, but not always done...

**Comment by ToddCooper** [comment]
@JavierEspina -- This entry should be moved to the Closed section of the issues document.
