### ISSUE TITLE
Device provider sample data generation

### ISSUE THREAD

**Issue by anweiss** [IHE/sdpi-fhir#13]
Brand new to the medical device ecosystem so apologies in advance for my naivety. I'm trying to wrap my head around 11073 SDC, FHIR and the Gemini SDPi+FHIR [effort](https://confluence.hl7.org/pages/viewpage.action?pageId=66926431) and the ["Hanging Gardens Framework"](https://confluence.hl7.org/display/GP/Hanging+Gardens+Framework). I'm inquiring on whether or not there are any device provider data generation tools out there. So for example, are there any tools to generate data conformant to 11073-10103 for implantable cardiac devices (ICD)? Or maybe asking another way, do any IHE PCD profiles exist for 11073-10103 ICDs? ... I think I'm asking the right question?? lol ... Apologies again for my terse understanding. Seems like a lot is still in flux. Thanks!

**Comment by ToddCooper** [comment]
Short answer:  No current ICD data generators that I know of.  But ask the IHE DEV IDCO group! 
Longer(ish) answer:  IDC's are currently out of scope for the Gemini SDC/SDPi+FHIR program.  We will have simulators at some point to generate data for the modalities that are of greatest interest; however, that is still a bit in the future (like 2023 range).
