### ISSUE TITLE
SDC to IHE DEV DEC Gateway

### ISSUE THREAD

**Issue by ToddCooper** [IHE/sdpi-fhir#157]
Craft the content for the TF-2 Appendix B DEC Gateway section.

**Comment by ToddCooper** [comment]
@PeterKranich:  Thinking about that first section in TF-2 Appendix B Gateways, the one with the mappings that are shared between the DEC and ACM gateways, you said that to reduce duplication of identical content + to ensure that the two gateway actor specifications are complete (so you don't have to flip between sections to get the whole picture) the shared content was captured in include files that can be pulled into each of the specific gateway specifications.  Understood.

I still think that it would be good to have that first section provide a simple overview of what is comment for SDC-to-V2.  Including either a summary of the shared content or better yet, just include those files also in the initial section.  Shouldn't be much work and will IMHO enhance the overall content of the appendix.

**Comment by PeterKranich** [comment]
> I still think that it would be good to have that first section provide a simple overview of what is comment for SDC-to-V2. Including either a summary of the shared content or better yet, just include those files also in the initial section. Shouldn't be much work and will IMHO enhance the overall content of the appendix.

@ToddCooper: sound reasonable for me. I will create another issue for that task.
