### ISSUE TITLE
TF-1 Appendix B - Referenced Standards does not exclusively contain referenced standards

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/sdpi-fhir#194]
For example:

- IHE PCD SDPi Use Cases Compendium
- IHE EU Experience-2021 IHE CA for MedTech Solutions
- IHE PCD SDPi White Paper:2019

We should rename this clause or come up with an additional clause for any bibliography (similarly to how it is done in IEEE standards where there is a clause "Normative references" and "Bibliography").

**Comment by ToddCooper** [comment]
See discussion notes from [SDPi Friday 18.11.2022](https://confluence.hl7.org/display/GP/Gemini+2022-11-18+SDPi+Friday).
