### ISSUE TITLE
Implement figure and table numbering in accordance with IHE policies

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/sdpi-fhir#205]
Currently, the Asciidoc converter cannot produce numbering for figures and tables that is valid in terms of IHE guidelines. This ticket is a reminder to implement the numbering.

This issue is the same as: #180

**Comment by d-gregorczyk** [comment]
Currently, the Asciidoc converter cannot produce numbering for figures and tables that is valid in terms of IHE guidelines. This ticket is a reminder to implement the numbering.

**Comment by ToddCooper** [comment]
IHE style guide for numbering figures and tables is as follows:
- Base number is the same as the enclosing section number
- Add a dash and sequence number for each figure or table (separate sequences)
For example, if section 1.2.3 has two figures and one table, they would be numbered as follows:
- Figure 1.2.3-1
- Figure 1.2.3-2
- Table 1.2.3-1 
The challenge is when crafting section external references to these tables.  For example, TF-1 Figure 1.2.3-2 may be referenced in TF-2 section 3.23.  A mechanism needs to be crafted that enables, for example, the asciidoc-converter to resolve these external figure references based on the final figure numbering.
