### ISSUE TITLE
Append ToI: System Types Nomenclature

### ISSUE THREAD

**Issue by PeterKranich** [IHE/sdpi-fhir#214]
<html>
<body>
<h2 id="Topic:SystemTypesNomenclature-CentralSDCServiceParticipants" style="margin: 30px 0px 0px; padding: 0px; font-weight: normal; text-transform: none; font-size: 20px; line-height: 1.5; letter-spacing: -0.008em; color: rgb(23, 43, 77); border-bottom-color: rgb(255, 255, 255);"><strong>Central SDC Service Participants  </strong></h2><p style="margin: 10px 0px 0px; padding: 0px;">Central (i.e., provider of general services used by many different CONSUMERS) SDC PROVIDER SERVICE PARTICIPANTs might have been connected to a SDC PARTICIPANTs network providing common services to other SDC CONSUMER SERVICE PARTICIPANTs. In order to discovery these services on the network, the discovery message shall contain the following identifiers for the corresponding services:</p><div class="table-wrap" style="margin: 10px 0px 0px; padding: 0px; overflow-x: auto;">

MDS Type | Identifier | Description
-- | -- | --
Gateway | tbd code | Gateway PARTICIPANT that provides, for example, ADT information or laboratory results (inbound)
SmartAlerting | tbd code | Smart Alerting system that provides consolidated alert event (actionable alerts), advisories such as patient deteriorations, etc.
Device Aggregator | tbd code | Discovering devices that are integrated to an SDC network aggregator (see discussion below)
  |   |  

</div><p style="margin: 10px 0px 0px; padding: 0px;"><br style="color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>

For further information see https://confluence.hl7.org/display/GP/Topic%3A+System+Types+Nomenclature.

**Comment by ToddCooper** [comment]
A TF-3 section "System Type Nomenclature Extensions" has been added and extended per system & service types called out in the TF-1 Appendix C Use Case specifications.
