### ISSUE TITLE
Substitution Not Performed In Section Titles

### ISSUE THREAD

**Issue by ToddCooper** [IHE/sdpi-fhir#229]
Text substitutions are not performed in section titles.  For example:  
"C.2.4.2 Scenario: STAD 1.2 - Device is connected to network with a <a href="#acronym_ts_service">TS Service</a> and a second device’s time setting is changed manually" 
in tf1-ch-c-use-case-stad.adoc.

**Comment by d-gregorczyk** [comment]
I wasn't able to reproduce this error. Latest Master seems to be correct, my local test runs all produced correct output. Maybe I looked at the wrong line in the document. Do you see the bug in here? https://github.com/IHE/sdpi-fhir/actions/runs/3747427908
