### ISSUE TITLE
SDPi 1.0 Use Case Labels & Acronyms Not Referencing Properly

### ISSUE THREAD

**Issue by ToddCooper** [IHE/sdpi-fhir#243]
Addition to Appendix C of use case labels and acronyms (e.g., via [[use_case ...]] or [[acronym_stad]]) resulted in AsciiDoc reference errors.

Adding them to the end of the Glossary file and commenting them out of the use case files did not help.

How and where should these be defined?

**Comment by d-gregorczyk** [comment]
I cannot reproduce this without more information. Could you setup a branch that provokes the reference errors? Thanks!

**Comment by ToddCooper** [comment]
Addressed in a separate issue.
