### ISSUE TITLE
Missing reference to SDC

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#246]
## Section Number

Introduction to this Supplement

## Priority

Low

## Issue

Why do we reference FHIR but not the IEEE 11073-SDC standards that are used throughout the document? 

## Proposed Change

Add a reference to IEEE 11073-10201, IEEE 11073-10207 and IEEE 11073-20702

**Comment by ToddCooper** [comment]
This is required IHE Supplement boilerplate / template content that we cannot change.
