### ISSUE TITLE
Too much content in 'SDPi "Topic of Interest" Issue Management' chapter

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#247]
## Section Number

SDPi "Topic of Interest" Issue Management

## Priority

Medium 

## Issue

I like the introduction in this chapter as it provides a lot of transparency into the development process. But I'm unsure what we want to achieve with the two following sections.

**Open Issues and Questions**: This will probably be outdated the moment this version is published. Also, the level of detail and the knowledge required to understand these issues might be problematic for people getting started in SDPi. Instead of providing details on so many different topics in the introduction, we should probably just keep the reference to the IHE Github sdpi-fhir repository Issues section in the introduction to this chapter. This is easier to maintain, expert users can still get all the information they need, and beginners are not confused unnecessarily. 
**Closed Issues**: Why do we have this in version 1.0? in later versions, there might be a need for some kind of change log but I wouldn’t expect to see one in the first version. If we keep it, the ToDos need to be removed and issues need to be described in more detail.

## Proposed Change

Delete "Open Issues and Questions" and "Closed Issues" chapters.

**Comment by ToddCooper** [comment]
These two sections are mandatory for IHE supplements and may not be deleted.  They will not be included in the "final text" versions that are integrated into the IHE DEF TF.  

Actually, integration of this work into Github issues is a huge improvement over previous approaches to IHE supplements, and is analogous to what is being advanced in a few other domains such as ITI.
