### ISSUE TITLE
BICEPS Content Creator vs. SOMDS Provider

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#248]
## Section Number

Volume 0 Appendix A: Actor Summary Definitions

## Priority

High

## Issue

What is the difference between a BICEPS Content Creator and a SOMDS Provider? First, I thought that the SOMDS Provider is a medical device while the Content Creator doesn't need to be. But this does not work with the SERVICE PROVIDER definition from BICEPS as referenced in the SOMDS Provider definition. The same question applies to the BICEPS Content Consumer vs. SOMDS Consumer actors. 

## Proposed Change

Please clarify definitions

**Comment by AnnaFeiler** [comment]
Any changes in the definitions also need to be reflected in chapter 10.1. I don't understand why we would need a seperate BICEPS Content Creator that is not a SOMDS Provider here. Any device interacting on the network should be required to be at least a SOMDS Provider.

**Comment by ToddCooper** [comment]
BICEPS Content Provider / Consumer actors are aligned with IHE actor naming convention for content-focused actors that are agnostic to the various means by which the content might be exchanged (thus the cloud between the two actors).  Note that the descriptions in the Appendix A are intentionally brief - they are for a broad audience.

All of the SDC protocol exchange actors are pre-pended with SOMDS which then results in disambiguation between duplicates with the SDC defined components with others in IHE profiles -- the TF-0:  Appendix A includes actors from across all IHE technical framework specifications.  

Looking at the actor descriptions in TF-1:SDPi-P profile (e.g., 10.1.1.9 BICEPS Content Creator), statements are included to make the role of the "cloud", for example:

> Note that although this SDPi-P content actor primarily supports information exchange between systems participating in a SOMDS network environment, they may also be utilized by other non-SDPi profiles that support non-SOMDS exchange architectures, transactions and technologies.

This should address the differentiation between these actors and that these actors are not need to be SOMDS Providers.
