### ISSUE TITLE
Feedback concerning requirements Management for Plug-and-Trust Interoperability

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#251]
## Section Number

Volume 1 Appendix A: Requirements Management for Plug-and-Trust Interoperability

## Priority

Medium

## Issue

Feedback as requested by the reviewer section:

I’m sure this will evolve to be a valuable part of device approval. However, I have two main concerns right now:
1.	Some of these topics may have a major impact on device development processes. We shouldn’t put in too many details right now without having had an in-depth discussion and a decision on the timeline for SDC device approval activities, conformity assessment, connectathons, …. 
2.	We still have a lot of ToDos in the core part of SDPi (Actor definitions, time sync to mention only a few). Let’s focus on those and keep this short for the time being. 

## Proposed Change

 (Admittedly somewhat radical) suggestion to the timeline: 
For now, keep A1 and the introduction and delete everything else.
Anything safety related (A2-A4) should be included in parallel to PKP integration activities.
A.5 & A.6: Can be added as soon as someone has time to write them, but it would be sufficient for me, if we added them in small increments over the following versions
I’d like to propose an additional topic to discuss concerning regulatory readiness: A lot of discussions boil down to a risk-benefit assessment. If we could somehow provide a description of a workflow/clinical benefit along with the use cases, this would help a lot in device approval especially if we are thinking about building a modular plug&trust system. I’m aware that this is not an easy since we will need proof especially if we claim clinical benefits (patients are cured faster, … ). Nevertheless, it is a discussion worth having and we should at least try to state obvious, non-clinical benefits (maybe something like: reduce likeliness of errors in certain clinical scenarios, prevent workflow interruptions by interchangeability of products, prevent gaps in documentation, … ).  This could be added whenever we add a use case.

**Comment by ToddCooper** [comment]
Noted.  Priority is given to completing the core technical specifications as pointed out -- actors, transactions, content specifications.  For SDPi 1.0, TF-1 Appendix A is primarily ensuring that there is a basic understanding of RI => RR, with a more complete description and implementation coming in later versions.  For example, 1.0 will not have a fully evolved requirements metamodel but it will include requirements sections (see TF-2 especially).  

As for clinical benefit associated with use case specifications, we can consider addition of an  additional section in the use case specification sections (yo, @kenjfuchs ).  

The PKP ICS tables will be included in 1.1 and later in Appendix B to flow risk management mitigation requirements forward to supporting sections with in the specification.

**Comment by AnnaFeiler** [comment]
@ToddCooper: As discussed yesterday, I've split this issue into two (see #317 for the clinical benefit part). The new one is tagged 1.x so we can focus on the feedback here.
@kenjfuchs: Let's discuss the benefit part some more in #317

**Comment by ToddCooper** [comment]
Agreed.  Updated content will be resolved as part of TF-1 completion before Public Comment.

**Comment by AnnaFeiler** [comment]
Just for maintanace: Done if #315 is done
