### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#256]
## Section Number

see Issue

## Priority

Low

## Issue
Introduction: Supplement Support for RI+MC+RR using AsciiDoc:  replace post-processi with post-processing
C.7.4.1: AGAGWW should be AGW
A.3.1.1: [OASIS WS-Discovery:2009]> remove ">" character?

## Proposed Change

fix typos

**Comment by ToddCooper** [comment]
Typos corrected in SDPi 1.0 DEV Internal Review v1

**Comment by ToddCooper** [comment]
Note:  These typo corrections were migrated to a new branch:  sdpi-1.0-dev-internal-review-v2
