### ISSUE TITLE
DEC Gateway: PID-6 Mother's Maiden Name Mapping

### ISSUE THREAD

**Issue by riechkathrin** [IHE/sdpi-fhir#257]
## Section Number

B.3.4.2.4

## Priority

Medium

## Issue

As specified in https://wiki.hl7.de/index.php?title=Segment_PID the field "Mother's Maiden Name" shall no longer be used.
"In the interpretations of previous versions of the standard "Mother's Maiden Name" lacking a corresponding field has been used for the maiden name of the patient. As of version 2.5 this is no longer allowed. Here the "patient's name" field taking advantage of repetitions shal be used."

## Proposed Change

The field PID-5 should be repeated. The Name Type Code is then set to "B" (name at birth).

**Comment by PeterKranich** [comment]
The IHE PCD TF-2 still requires this field to be used (also for backward compatibility):
![image](https://user-images.githubusercontent.com/33724235/216557016-b237b0de-f092-43f7-b9cc-d27b7b41e444.png)

![image](https://user-images.githubusercontent.com/33724235/216556820-656cb451-3522-44bd-8c61-8fc0490f518b.png)

Also in the HL7 V2.6 standard - on which the IHE TF-2 is based on -  the optionality of the field is marked as "O" (optional) and not as "B" (left in for backward comp...).

**Comment by riechkathrin** [comment]
My comment was not about the field itself being out of use. It is about the fact that there is a difference between Birthname and Mother's Maiden Name. It is therefore not ok to map the Birthname from SDC to Mother's Maiden Name.

**Comment by riechkathrin** [comment]
Birthame: A birth name is the family name someone has when he or she is born
Mother's Maiden Name: A mother's maiden name is the family name a mother has before she gets married.

**Comment by ToddCooper** [comment]
Discussion in the SDPi Friday meeting (2023.02.03), the group agreed to keep the specification as currently drafted, especially to support backward capabilities with existing DEC & ACM profiles implementations.
