### ISSUE TITLE
DEC Gateway: PV1-19 Visit Number Mapping

### ISSUE THREAD

**Issue by riechkathrin** [IHE/sdpi-fhir#258]
## Section Number

B.3.4.4.4

## Priority

Medium

## Issue

According to table 35 there is more than one valid identifier type code for the visit number. R8114 says only the unique identifier assigned to the patient’s visit is mapped. This needs clarification

## Proposed Change

I suggest to limit the valid identifier type code to "VN" (visit number).

**Comment by AnnaFeiler** [comment]
Covered by https://github.com/IHE/DEV.SDPi/issues/29
