### ISSUE TITLE
DEC Gateway: Prerequisite of Valid Patient Context

### ISSUE THREAD

**Issue by riechkathrin** [IHE/sdpi-fhir#259]
## Section Number

B.4.4.21

## Priority

Medium

## Issue

The requirement R8102 contains: "when the requirements (e. g. inferred patient ensemble context, associated patient context, etc.) ". This is not sufficiently specified. Which requirements need to be fullfilled? 
There should be no etc. in a requirement.

**Comment by PeterKranich** [comment]
@riechkathrin: I agree the requirement is not very specific. It refers to the requirements in the Base-PKP. I didn't listed the B-PKP requirements here in order not to get in to a tight dependency with the B-PKP. Let's discuss this further.

**Comment by PeterKranich** [comment]
To be fixed: move example in brackets into a note instead of the requirement text.

**Comment by AnnaFeiler** [comment]
partially duplicates: R8102 & R8111: improve wording and clarify, how to reference BPKP content #341
