### ISSUE TITLE
DEC Gateway: OBX-20 Observation Site Mapping

### ISSUE THREAD

**Issue by riechkathrin** [IHE/sdpi-fhir#260]
## Section Number

B.3.4.6.14

## Priority

Low

## Issue

There are mistakes in the mapping of OBX-20/CWE-2 and OBX-20/CWE-3. Thies field shall contain the bodysite, not the unit information.

## Proposed Change

The mapping for OBX-20/CWE-2 needs to replaced by pm:AbstractMetricState /pm:BodySite /@SymbolicCodeName.
The mapping for OBX-20/CWE-3 needs to replaced by pm:AbstractMetricState /pm:BodySite /@CodingSystem.

**Comment by PeterKranich** [comment]
Good catch! Thanks.
