### ISSUE TITLE
DEC gateway: Coding System identification

### ISSUE THREAD

**Issue by riechkathrin** [IHE/sdpi-fhir#262]
## Section Number

B.3

## Priority

Medium

## Issue

Normally a CodingSystem is specified by an oid. Which is done for all CodingSystems except "MDC". Shouldn't "MDC" then also be specified by urn:oid:1.2.840.10004.1.1.0.0.1?

## Proposed Change

Replace all CodingSystem mappings that contain "MDC" by urn:oid:1.2.840.10004.1.1.0.0.1

**Comment by PeterKranich** [comment]
Good point, but as of now the IHE PCD TF defines to use "MDC" as the coding system identifier:
![image](https://user-images.githubusercontent.com/33724235/216539354-d982ee49-ece0-4b4d-a63f-081d966b0d2a.png)

This may change in the future.
