### ISSUE TITLE
Timesync without clock object?

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#263]
## Section Number

Volume 3, chapter 8.3.2.2, SDPi Supplement Version Note

## Priority

Medium
## Issue

Maybe I'm missing something but how do we support a time synchronisation use case without supporting profiles for clock objects? Are they just not required, as BICEPS is sufficiently detailed? 

## Proposed Change

Is it really necessary to have this note? We support all content that is relevant for our use cases. If further use cases are added, we'll profile SDC content as needed. My suggestion would be to delete this note.

**Comment by ToddCooper** [comment]
@d-gregorczyk -- Please confirm the comment below.
My understanding is that NTP synchronization, which is required by the Consistent Time (CT) protocol that SPDI-P is dependent on (requires) does not require the Clock object.  The Clock provides additional capabilities + often simple devices do not contain a Clock function.

**Comment by AnnaFeiler** [comment]
@ToddCooper: I've had a short discussion with David. The clock object is already mandatory in BICEPS, so not supporting it, is not an option. If we just remove it from the note, everything should be fine.

**Comment by ToddCooper** [comment]
Accepted.  "Clock objects" removed from the TF-3 comment box.

The note does have value, though, for those who are familiar with the BICEPS model, see what is actually profiled in the 1.0 BICEPS sections and ask, "What about <xyz>?"  Given that this is a "version" note, it will disappear in subsequent versions as more complete coverage of the profiling of BICEPS is contained in TF-3.

**Comment by ToddCooper** [comment]
Issue closed with approval of PR #312
