### ISSUE TITLE
MDIB Report Retrofit / Best Practices

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#270]
## Section Number

Issue: MDIB Report Retrofit / Best Practices

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

AFAIK, this topic is closed with SDPi 1.0 (it's just the TOI page which is not updated on the status). 

## Proposed Change

Propose to move this one to close issues section below.

**Comment by ToddCooper** [comment]
Accepted; section moved to Closed issues + added references to the two "retrofit" sections that were added to address this topic.
