### ISSUE TITLE
SDPi-xC with Mixed Device Safety Classes 

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#271]
## Section Number

Issue: SDPi-xC with Mixed Device Safety Classes

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

Typos. Propose to change to "if it WILL be explicitly resolved".

## Proposed Change

Propose to change to "if it WILL be explicitly resolved".

**Comment by ToddCooper** [comment]
Accepted and correction made.
