### ISSUE TITLE
TF0- Appendix A - "Alert Aggregator" Used in Specification?

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#272]
## Section Number

TF0- Appendix A

## Priority

Low/Medium

## Issue

I don't see that the Alert Aggregator is used. However the ACON, AM and AR are.

## Proposed Change

Propose to delete Aggregator row in Table TF-0:B-8.
Also propose the TBD bold note from the ACON and AM rows.

**Comment by ToddCooper** [comment]
"Alert Aggregator" is used in the definition of Alert Reporter.   It is also defined in the [TF-0 Appendix A Actors](https://gazelle.ihe.net/GMM/tf/actor/listActors.seam) list.  As noted in the entry, it may end up referenced in the ACM Gateway specification; however, in the current IHE DEV TF (final text) ACM spec, it is not defined as a formal actor.  

For SDPi 1.0, it is appropriate to include it given its reference in Alert Reporter; however, this could be the subject of later discussion, not just in the SDPi specification but in ACM and whether it should be retained in the TF-0 Appendix A list or not.

**Comment by JavierEspina** [comment]
> "Alert Aggregator" is used in the definition of Alert Reporter. It is also defined in the [TF-0 Appendix A Actors](https://gazelle.ihe.net/GMM/tf/actor/listActors.seam) list. As noted in the entry, it may end up referenced in the ACM Gateway specification; however, in the current IHE DEV TF (final text) ACM spec, it is not defined as a formal actor.
> 
> For SDPi 1.0, it is appropriate to include it given its reference in Alert Reporter; however, this could be the subject of later discussion, not just in the SDPi specification but in ACM and whether it should be retained in the TF-0 Appendix A list or not.

OK. Agree with the resolution. Thx!
