### ISSUE TITLE
UML notation for asynchronous messages with non-filled arrow

### ISSUE THREAD

**Issue by MartinKasp** [IHE/sdpi-fhir#274]
## Section Number

Entire document 

## Priority

Medium

## Issue

According to UML Spec v2.4.1 Table 14.2 asynchronous messages are modelled as arrows with not filled arrow end and solid line.

## Proposed Change

Change all asynchronous messages (notifications) accordingly in PlantUML
`Bob ->> Alice `

**Comment by ToddCooper** [comment]
Changes made to:  puml-sdpi-p-example-sequence-diagram.puml

**Comment by MartinKasp** [comment]
![image](https://user-images.githubusercontent.com/112488805/216637369-5d44fc42-b699-40d0-ae72-dfe44fe85b3f.png)

As discussed during today’s web meeting:

- Green highlights should be the open/non-solid arrows as in the new proposal
- Blue highlights should be the solid arrows like in this picture

Additionally: The response lines are currently dotted. If possible, it should be dashed. (Purple in the attached figure)

**Comment by MartinKasp** [comment]
As discussed during today’s web meeting:
"Discover Network Topology" should be part of the "unsecured" part.

**Comment by ToddCooper** [comment]
@MartinKasp  -- Updates made to the branch.

**Comment by ToddCooper** [comment]
Updated diagram has been merged to master via a general comment resolution branch ( #312).

**Comment by ToddCooper** [comment]
There are still PUML diagrams in TF-2 ...
