### ISSUE TITLE
TF-1 2.3.1 "Figure Figure" - remove duplication

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#275]
## Section Number

2.3.1 Service-oriented Device Point-of-care Interoperability (SDPi) – Overview & Framework

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

Remove first "Figure" in "in Figure Figure 2.3.1-1. IHE SDPi Profiles & Foundational Standards"

## Proposed Change

Remove first "Figure" in "in Figure Figure 2.3.1-1. IHE SDPi Profiles & Foundational Standards"

**Comment by ToddCooper** [comment]
Duplicate "Figure" removed
