### ISSUE TITLE
TF-1 2.3.x - Confusing Reference to SDPi-P profile

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#277]
## Section Number

2.3.11 Service-oriented Device Point-of-care Interoperability - Reporting (SPDi-R) Profile

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

"builds on the basic PnT profile" seems an unnecessarily confusing way of referring to the SDPi-P profile.

## Proposed Change

Propose to change text  to "builds on the basic SDPi-P profile" in 2.3.11, 2.3.12, and 2.3.13.

**Comment by ToddCooper** [comment]
Text updated with addition of "SDPi-P" acronym & "builds on the basic PnT capabilities of the SDPi-P profile".
