### ISSUE TITLE
TF-1:10.1-1 Table - Inconsistent use of "Consumer" Actor

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#279]
## Section Number

Table 10.1.20. SDPi-P Profile - Actors and Transactions. Sentence "Note that "Consumer"...".

## Priority

Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

## Issue

There may be some inconsistency here. "Consumer" is not used in the table (column "Initiator or Responder"). In additionthe table has two instances of "receiver", which is not mentioned in the explanation or the column title. Was the intend to write Consumer where it says Receiver? And why is there a difference in responsiveness between getting a Hello/departure message (DEV-23, -34) and getting a BICEPS report update (DEV-29)?

## Proposed Change

Please explain and correct as needed

**Comment by ToddCooper** [comment]
NOTE:  In the current master branch, TF-1 **_Table 10.1-20_** is now Table **_TF-1:10.1-1_**.

Comment not clear:  SOMDS Consumer is used in the table ... ?   The actor name though is different from its IHE role as an Initiator or Responder, as indicated in this column, which is part of the IHE template for this table.

The use of "receiver", though, is confusing, compounded by its being listed in _italics "Receiver"_ with no further description.  A note was added to the table for both instances of _Receiver_ indicating the nuance.

**Comment by JavierEspina** [comment]
> NOTE: In the current master branch, TF-1 **_Table 10.1-20_** is now Table **_TF-1:10.1-1_**.
> 
> Comment not clear: SOMDS Consumer is used in the table ... ? The actor name though is different from its IHE role as an Initiator or Responder, as indicated in this column, which is part of the IHE template for this table.
> 
> The use of "receiver", though, is confusing, compounded by its being listed in _italics "Receiver"_ with no further description. A note was added to the table for both instances of _Receiver_ indicating the nuance.

Good changes and explanations. Thx! Please forget the part about missing "consumer" in the table.
The last part of my comment remains though. Now extended for completeness:
"Why is there a difference in responsiveness between getting a Hello/departure message (DEV-23, -34 , marked as receiver) and (DEV-28, DEV-29, DEV36, and DEV-39)? In none of the four latter transactions is a response expected, as far as I can tell.

**Comment by JavierEspina** [comment]
As discussed on the Feb3 SDPi call, DEV-28, DEV-29, DEV36, and DEV-39 will be marked as Receiver instead of Responder.
