### ISSUE TITLE
TF-1 Figure 10.1-3 - Remove Duplicate "SOMDS Provider"

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#280]
## Section Number

Figure 10.1-3 explanation. Sentence "In general, a SOMDS ProviderSOMDS Provider actor will create content".

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

Duplication in "In general, a SOMDS ProviderSOMDS Provider actor ". 

## Proposed Change

Remove duplication.

**Comment by ToddCooper** [comment]
Correction made.
