### ISSUE TITLE
TF-1:10.1.1.1 - SFC Reference Does Not Exist

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#281]
## Section Number

10.1.1.1
Sentence "See #A.3 Specifying SystemFunctionContribution (SFC) for Plug-and-Trust Interfaces for more information."

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

Missing section.

## Proposed Change

 Remove sentence?

**Comment by ToddCooper** [comment]
Replaced core text with reference to term definition in the Glossary.  Added a link to the TF-1 Appendix A discussion around clinical system functions, etc.
