### ISSUE TITLE
TF-1 10.4.1.1 - Reword "An example of ..."

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#283]
## Section Number

10.4.1.1

## Priority

Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

## Issue

 " An example of how BICEPS components..." -> Grammar needs improvement. 

## Proposed Change

Propose to start with "For an example..."

**Comment by ToddCooper** [comment]
Sentence reworded for clarity ... and proper - or more proper-er-er-er- ... grammar
