### ISSUE TITLE
Collected Comments on Volume 0 Appendix B and D

### ISSUE THREAD

**Issue by MartinKasp** [IHE/sdpi-fhir#289]
First of all, I like to repress my deep appreciation for the work that has been done in this section. **Great job!** Thus, please do not misunderstand the number of comments I made. 

Please find my comments in the attached PDF file. 

[_Volume_0_Appendix_B - sdpi-supplement.html-comments_MK_v01.pdf](https://github.com/IHE/sdpi-fhir/files/10464676/_Volume_0_Appendix_B.-.sdpi-supplement.html-comments_MK_v01.pdf)

**Comment by ToddCooper** [comment]
Note the comment (a mis-aligned Transactions table) was resolved per an earlier comment.

Comment resolutions are in the attached PDF file.

[_Volume_0_Appendix_B.-.sdpi-supplement.html-comments_MK_v01_THC1.pdf](https://github.com/IHE/sdpi-fhir/files/10560247/_Volume_0_Appendix_B.-.sdpi-supplement.html-comments_MK_v01_THC1.pdf)

**Comment by MartinKasp** [comment]
@ToddCooper The attached PDFonly contains one reply from you. Thus, it is difficult to decide whether you rejected a comment for reasons of content, pushed it to SDPi 1.x/2.x or it is still on the to-do list.

**Comment by ToddCooper** [comment]
@MartinKasp  - Due to the way the PDF was titled ("Appendix_B") and seeing an expanse of white space after the Appendix B table, I assumed that that was the end of the PDF, addressed the single Appendix B comment and went on, not realizing that there was an Appendix D section lurking below!   

I will review and resolve the Appendix D comments now.

**Comment by MartinKasp** [comment]
@ToddCooper ohh... sorry, my fault :-/

**Comment by ToddCooper** [comment]
Combined comments PDF with resolutions to TF-0 Appendix D:
[_Volume_0_Appendix_B.-.sdpi-supplement.html-comments_MK_v01_THC2.pdf](https://github.com/IHE/sdpi-fhir/files/10679021/_Volume_0_Appendix_B.-.sdpi-supplement.html-comments_MK_v01_THC2.pdf)

Updated text pushed to PR #312  

@MartinKasp - Please review the proposed resolutions and updates ... and hopefully, approve the PR!

**Comment by ToddCooper** [comment]
@d-gregorczyk :  The following comment was made by @MartinKasp  at the end of this TF-0 Appendix D review:

> Is this really a physical address? A MAC address comes into my mind when I hear physical endpoint address. 
The XAddr, which must be an HTTP or HTTPS address, is more logical in my opinion. There can be more than one XAddr for one physical endpoint. 

Glossary entry:  Transport Address
Term description:  A physical endpoint address that can be used to communicate with a SOMDS Provider.
Synonym:  xAddr

My guess is that you (@d-gregorczyk ) were the source of this language ... I most assuredly was not!

**Comment by d-gregorczyk** [comment]
The naming stems from

> DPWS: R5009: If a DEVICE uses a physical transport address for the [address] property of its Endpoint Reference, it MUST be an HTTPS scheme IRI.

I think a physical address is an address that can be resolved to a physical endpoint (like an IP or MAC address). Me personally, I have no strong opinions on the naming, it should reflect the fact that a transport address is an address to which a network peer can establish a connection (which is not the case for, e.g. URNs).

**Comment by ToddCooper** [comment]
Thanks, David.  that's what I assumed was the source.

So - is there any proposed wording change to what is currently in the
document?  Or leave it as is?  Or add a 2nd sentence to clarify?

~>Todd 탇

*Soli Deo gloria*

M:  +1 858.442.9200
S:  ToddCooperAFC

**Comment by ToddCooper** [comment]
Closed with the approved merge of the comments from this issue (see #312 ).  If the current wording needs to be changed especially before the Trial Implementation, then it can be reopened.
