### ISSUE TITLE
Collected Comments on Volume 0 Appendix A

### ISSUE THREAD

**Issue by MartinKasp** [IHE/sdpi-fhir#290]
First of all, I like to repress my deep appreciation for the work that has been done in this section. Great job! 

Please find my comments in the attached PDF file.

[_Volume_0_Appendix_A - sdpi-supplement.html-comments_MK_v01.pdf](https://github.com/IHE/sdpi-fhir/files/10465070/_Volume_0_Appendix_A.-.sdpi-supplement.html-comments_MK_v01.pdf)

**Comment by ToddCooper** [comment]
All comments accepted in principle & replies added to the attached PDF.  

Note that the updates have been made to branch [sdpi-1.0-dev-internal-review-v3](https://github.com/IHE/sdpi-fhir/tree/sdpi-1.0-dev-internal-review-v3/SDPi_Supplement).

[_Volume_0_Appendix_A.-.sdpi-supplement.html-comments_MK_v01_THC1.pdf](https://github.com/IHE/sdpi-fhir/files/10559875/_Volume_0_Appendix_A.-.sdpi-supplement.html-comments_MK_v01_THC1.pdf)

**Comment by ToddCooper** [comment]
Update SOMDS Consumer & SOMDS Provider actor brief descriptions (TF-0 Appendix A) to indicate their relationship to BICEPS Content Consumer & BICEPS Content Creator respectively.
