### ISSUE TITLE
Exaggerated expectations are created: Supplement Support for RI+MC+RR using AsciiDoc

### ISSUE THREAD

**Issue by MartinKasp** [IHE/sdpi-fhir#291]
## Section Number

Supplement Support for RI+MC+RR using AsciiDoc

## Priority

Medium

## Issue

According to the glossary, this is synonym to "Model-Based Systems Engineering". 
While the development process of this document is a huge step in the right direction, we are light years away from MBSE which just using AsciiDoc. However, the heading suggest that we believe using AsciiDocs brings us to MBSE. 

In my opinion, this has never been the goal of using AsciiDoc.

I know, the wording is "support", however, there is lots of space for misinterpretation.

## Proposed Change

Reduce expectations and clarify that AsciiDoc is only a very very small building block along the way.

**Comment by ToddCooper** [comment]
Accepted in principle & per the 27 January "SDPi Friday" discussion, updates were made to both the section indicated above and the Glossary entries:

1. Glossary entry for Model-Centric was added and decoupled from the MBSE entry, thus reducing the linkages between the two and adding clarity.
2. Glossary entries for RI / MC / RR are appropriately synchronized and linked, adding clarity
3. Supplement Intro section language updated to clearly indicate that SDPi 1.0 represents "a small step" in the RI+MC+RR direction and that it will take considerable time and effort to realize these objectives.
