### ISSUE TITLE
Introduce Abbreviation CA

### ISSUE THREAD

**Issue by MartinKasp** [IHE/sdpi-fhir#292]
## Section Number

Supplement Support for RI+MC+RR using AsciiDoc

## Priority

Medium

## Issue

Abbreviation has never been introduced and is not clear to me in this context. 

CA = Conformity Assessment?

## Proposed Change

Introduce Abbreviation CA

**Comment by ToddCooper** [comment]
Added the term & acronym to the Glossary & linked to the referenced section.
