### ISSUE TITLE
Uses cases wrongly called profiles

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#293]
## Section Number

10.4.2. 11.4.2, 12.4.2

## Priority

Low

## Issue

"Specific capabilities supporting the STAD profile include:" -> STAD is a use case, not a profile.

## Proposed Change

Propose to replace "profile" with "use case" in all 6 sub-sections of 10.4.2, all 3 sub-sections of 11.4.2, and all 4 sub-sections of 12.4.2.

**Comment by ToddCooper** [comment]
Accepted.  Updates added to branch [sdpi-1.0-dev-internal-review-v3](https://github.com/IHE/sdpi-fhir/tree/sdpi-1.0-dev-internal-review-v3/SDPi_Supplement).
