### ISSUE TITLE
Copy-paste error in SDPi-xC profile

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#295]
## Section Number

13.1

## Priority

Low

## Issue

"Figure 13.1-1 shows the actors directly involved in the SDPi-R Profile" -> Copy-paste error. 

## Proposed Change

Correct to read SDPi-xC.

**Comment by ToddCooper** [comment]
This too was a class of issues around adding block anchors for figures and tables and then properly referencing them in the text.
Typo's corrected (there were numerous SDPi-xyz typos and mis-references) + added figure and table and clause references consistently across all (4) profiles.
