### ISSUE TITLE
Xml marks exposed in caption text

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#296]
## Section Number

TF-1, A.2

## Priority

Low

## Issue

Xml marks exposed in caption text (Figure A.2-12. ISO/IEC 81001-1 <em>The Temple Diagram</em>)

## Proposed Change

Remove <em> and </em>

**Comment by ToddCooper** [comment]
Figure caption updated to remove underscore markup.  New text:  The "Temple" Diagram  

Not sure why underscore markup <em>... </em> was not interpreted in the caption.  

@d-gregorczyk  - any idea of how to do this?
