### ISSUE TITLE
B.3.4.6.4 OBX-4 Observation Sub-ID mistake

### ISSUE THREAD

**Issue by riechkathrin** [IHE/sdpi-fhir#301]
## Section Number

B.3.4.6.4 OBX-4 Observation Sub-ID

## Priority

Medium

## Issue

R8014 requires the containment tree to be **flattened**. R8015 on the other hand requires the **hierarchical** representation of the containment tree. According to IHE PCD TF-2 there is a difference!

## Proposed Change

Use the hierarchical presentation as in the example.

**Comment by PeterKranich** [comment]
@riechkathrin: please re-evaluate your comment.

The IHE TF-2 states:
B.8.1 OBX-4 in a 'flattened' representation of a device
A 'map' of the hierarchical structure of the device representation, in other words the 2765 device's containment tree can be constructed from the set of OBX-4 values in a full observation report of all metrics the device produces. The highest (most inclusive) hierarchical level is the Medical Device System (MDS), representing the whole device. In the simplest, "flattened", representation of a device, it is the only level that is present. In the flattened representation, no Virtual Medical Devices (VMD) and no channels are 2770 identified in the hierarchy. Every metric is treated as contained only by the MDS, and it has an OBX-4 value of <n>.0.0.<m>, where <n> is the unsigned number chosen to identify the MDS (for simplicity, our examples will use 1 to identify the first or sole MDS, but other numbers may be applied), and the unsigned number <m>identifies the particular metric, and must be different for each metric. The flattened representation has 2775 only one device-related OBX segment, the one representing the MDS.

So, I don't understand what is wrong with the requirements and the example.

**Comment by PeterKranich** [comment]
To be fixed: flattened only for devices with no VMD and Channel.
