### ISSUE TITLE
B.3.4.6.7 OBX-7 Reference Range Mapping

### ISSUE THREAD

**Issue by riechkathrin** [IHE/sdpi-fhir#302]
## Section Number

B.3.4.6.7 OBX-7 Reference Range

## Priority

Medium

## Issue

A channel cannot have a TechnicalRange. 

## Proposed Change

Each OBX segment shall use the TechnicalRange of the **metric** measurement it refers to.

**Comment by PeterKranich** [comment]
@riechkathrin: can you please re-evaluate the issue?

The IHE TF-2 states:
OBX-7 Reference Range
For metric related segments, this should be used to provide the value ‘alarm’ ranges set with respect to the observed value metric in this OBX, although this is not strictly a reference range in the sense of the examples given in HL7.
**For device related segments this may be used to provide the device measurement range capability – NOT the metric value ‘alarm’ ranges which shall be in the appropriate observed value metric OBX, as indicated above.**

Device related segments refers to Channels, VMDs, and MDSs.

**Comment by PeterKranich** [comment]
To be fixed: do not support reference ranges on channel level. Add an explanation why this is not supported (different numeric metric under same channel with different ranges).
