### ISSUE TITLE
Possible typo in requirement type attribute "mdi_requirement_use_case

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#305]
## Section Number

TF-1, A.6.1

## Priority

Low

## Issue

Possible typo in requirement type attribute "mdi_requirement_use_case".

## Proposed Change

Should it read "sdpi_requirement_use_case"?

**Comment by ToddCooper** [comment]
Text changed per suggestion.  The recommended change makes the label consistent with the others in that column.

Note:  It wasn't a "typo" but was intentional given the use of DPI & MDI elsewhere in the document -- perhaps in a confusing vs. stylistic way!
