### ISSUE TITLE
Can't find a definition of ME in this supplement

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#306]
## Section Number

TF-1, C.1.5.2.1 (...that involves equipment in a ME SYSTEM)

## Priority

Low

## Issue

I know this section comes from 60601-1-8...but what is an ME system? I can't find a definition of ME in this supplement.

## Proposed Change

Explain acronym where most appropriate?

**Comment by ToddCooper** [comment]
There is the bigger question of how much of this excerpt from the ISO/IEC 60601-1-8 standard can be quoted here, as indicated by a #TODO note immediately before the section.  To address this comment, that note has been expanded with the following: 

     "ALSO NEED TO ADD DEFINITIONS FOR TERMS SUCH AS ME SYSTEM, ME EQUIPMENT, ETC."
