### ISSUE TITLE
C.2.4.2 and C.2.4.3 scenario titles display incorrectly

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#307]
## Section Number

C.2.4.2 and C.2.4.3 scenario titles

## Priority

Low

## Issue

C.2.4.2 and C.2.4.3 scenarios titles display incorrectly

## Proposed Change

Correct

**Comment by ToddCooper** [comment]
section title updated with "hard coded" text vs. use of a label.

NOTE:  This is a general issue where variables are expanded in section labels but not [[...]] definitions.
