### ISSUE TITLE
State the benefit of use cases more explicitly

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#317]
## Section Number

Volume 1 Appendix A: Requirements Management for Plug-and-Trust Interoperability

## Priority

Medium

## Issue

I’d like to propose an additional topic to discuss concerning regulatory readiness: A lot of discussions boil down to a risk-benefit assessment. If we could somehow provide a description of a workflow/clinical benefit along with the use cases, this would help a lot in device approval especially if we are thinking about building a modular plug&trust system. I’m aware that this is not an easy since we will need proof especially if we claim clinical benefits (patients are cured faster, … ). Nevertheless, it is a discussion worth having and we should at least try to state obvious, non-clinical benefits (maybe something like: reduce likeliness of errors in certain clinical scenarios, prevent workflow interruptions by interchangeability of products, prevent gaps in documentation, … ). This could be added whenever we add a use case.

## Proposed Change

Add benefits to use cases, for example Volume 1, Appendix C.2. Use Case Feature 1: Synchronized Time Across Devices (STAD): 
Could we put some more information here to stress the benefit of this use case (examples: all devices at the same workplace use the same time as a precondition for remote viewing, export to a gateway for consistent documentation…)?

**Comment by ToddCooper** [comment]
@AnnaFeiler  - Today @kenjfuchs  started work on the next linked branch #317 ... looking to get initial "benefits" text this week.
