### ISSUE TITLE
Device aggregator definition

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#327]
## Section Number

8.3.2.5, Table TF-3:8.3.2.5-1.

## Priority

Low

## Issue

Weird first sentence grammar (esp. verb tenses). Also "non-standardized" is not necessarily the case.

## Proposed Change

Improve grammar + replace "non-standardized" with "out of band"

**Comment by ToddCooper** [comment]
Definition reworded for clarity and readability - correct grammar!
