### ISSUE TITLE
Soft ID coded attribute code different in example & table

### ISSUE THREAD

**Issue by JavierEspina** [IHE/sdpi-fhir#329]
## Section Number

8.3.2.8.3 Coded Attribute

## Priority

Medium

## Issue

The Soft ID coded attribute code in Example 10 is 67886, which is different from the code specified in the table above for MDC_ATTR_ID_SOFT. Is this correct?

In fact it looks like the code in the table (8::7682) is wrong, as it does not mean MDC_ATTR_ID_SOFT....but MDC_ID_MODEL_MANUFACTURER. Copy-paste mistake?

## Proposed Change

Explain (in this ticket but ideally in a clarifying note in the SDPi draft) or correct.

**Comment by ToddCooper** [comment]
Confirmed the discrepancy between the table entry and the example, and confirmed that the example was correct.  Table entry updated to match example and to match the [Topic of Interest - Attribute Type Codes table entry](https://confluence.hl7.org/pages/viewpage.action?pageId=86970698#Topic:Infoexchangedduringunsecureddiscovery-AttributeTypeCodes).  Also, verified values against the 11073-10101:2004 nomenclature.
