### ISSUE TITLE
Topic: Connect Time Delay Algorithm

### ISSUE THREAD

**Issue by ToddCooper** [IHE/sdpi-fhir#33]
[(Complete Discussion for ***Topic:  Connect Time Delay Algorithm***)](https://confluence.hl7.org/display/GP/Topic%3A+Connect+Time+Delay+Algorithm) 

# **Issue Description**
*pull content from confluence page*

# **Issue Resolution**
*pull content from confluence page*

**Comment by ToddCooper** [comment]
Note:  This issue will be the first one that we use as an example of how to integrate ToI Resolved items into the Closed Issues list of the spec.

**Comment by ToddCooper** [comment]
Update related [sdpi-supplement-issues.adoc](https://github.com/IHE/sdpi-fhir/blob/master/SDPi_Supplement/asciidoc/sdpi-supplement-issues.adoc)  item when complete, indicating where the updates were made or the branche(s) that captured the updates, as well as moving from OPEN to CLOSED lists if appropriate.

**Comment by d-gregorczyk** [comment]
Duplicates #103
