### ISSUE TITLE
Superfluous spaces in Table TF-2:B.3.3-60. Private Code Mapping

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#338]
## Section Number

Table TF-2:B.3.3-60. Private Code Mapping (CWE data type example)

## Priority

Low: 

## Issue

Systematic error: there is no space before the "/", e.g. between "pm:Type" and "/@..." or "/pm:" 

@PeterKranich mentioned, that this is intentional to help AsciiDoc conversion

**Comment by AnnaFeiler** [comment]
@d-gregorczyk : Could you please comment?

**Comment by PeterKranich** [comment]
@d-gregorczyk: will this wrap the something like "pm:PatientContextState/pm:Identification/@Extension" at the "/" and not in the middle of the word?

**Comment by ToddCooper** [comment]
SDPi Friday 10 February discussion reviewed @PeterKranich 's comment above ... 

Also, [from AsciiDoc instruction](https://docs.asciidoctor.org/asciidoc/latest/blocks/hard-line-breaks/#:~:text=blocks%20and%20paragraphs.-,Inline%20line%20break%20syntax,br%3E%20)%20following%20the%20line.)s:
        [%hardbreaks]" kombiniert mit einem Enter, da wo du das Megawort trennen moechtest 

Another option is:  <wbr> HTML 

@d-gregorczyk  will review both of the above and see which works best & push to #338
