### ISSUE TITLE
R8102 & R8111: improve wording and clarify, how to reference BPKP content

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#341]
## Section Number

TF2 B.3.4.2.1:Prerequisite of Valid Patient Context 

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue R8102 & R8103

B.3.4.2.1 Prerequisite of Valid Patient Context
R8102 states 
_"The SDC patient context information shall only be mapped to the corresponding fields in the HL7 PID segment when the
requirements (e. g. inferred patient ensemble context, associated patient context, etc.) as defined in the [IEEE 11073-
10700:2022] are fulfilled.
If the SDC patient context information is not intended to be used for the mapping, please refer to the [IHE PCD TF-2:2019]
on how to populate the fields of the PID segment in this case."_

- Following our dicussion, this needs to change. Contexts shall only be used for mapping,if they are validated (= a validator present ) and associated
- please also move the e.g. ... part into a note

## Issue R8111
_R8111 states: 
"The SDC patient and location context information shall only be mapped to the corresponding fields in the HL7 PV1
segment when the requirements (e. g. inferred patient and/or location ensemble context, associated patient and/or
location context, etc.) as defined in the [IEEE 11073-10700:2022] are fulfilled._

If the SDC patient and/or location context information is not be used for the mapping, please refer to the [IHE PCD TF-
2:2019] on how to populate the fields of the PV1 segment in this case."
- Following our dicussion, this needs to change. Contexts shall only be used for mapping,if they are validated (= a validator present ) and associated
- please also move the e.g. ... part into a note

# Issue R8102:
_R8102
The SDC patient context information shall only be mapped to the corresponding fields in the HL7 PID segment when the
requirements (e. g. inferred patient ensemble context, associated patient context, etc.) as defined in the [IEEE 11073-
10700:2022] are fulfilled.
If the SDC patient context information is not intended to be used for the mapping, please refer to the [IHE PCD TF-2:2019]
on how to populate the fields of the PID segment in this case._

- Following our dicussion, this needs to change. Contexts shall only be used for mapping,if they are validated (= a validator present ) and associated
- please also move the e.g. ... part into a note

**Comment by AnnaFeiler** [comment]
derived from: #288 @MartinKasp: Could you make a suggestion?

**Comment by AnnaFeiler** [comment]
This was changed following a discussion between @MartinKasp, @PeterKranich , @riechkathrin and @AnnaFeiler

**Comment by PeterKranich** [comment]
@AnnaFeiler, @riechkathrin: I would propose to close this issue. This issue is fixed with #259 and #349.
