### ISSUE TITLE
Precondition for patient context HL7 mapping

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#351]
## Section Number

TF2 B.3.4.2.8 PID-31 Identity Unknown Indicator

## Priority

- *High: Important issue where there is major issue to be resolved. Requires discussion and debate.*

## Issue

R8109 currently states that patient data can only be mapped to HL7, if there is an associated patient-inferred ensemble context. This might be too restrictive.   

## Proposed Change

Discuss, if using a validated patient context might also be feasible

**Comment by AnnaFeiler** [comment]
@MartinKasp : This is one of your comments from IHE/sdpi-fhir#288. Since we've left the whole ensemble/device coupling/pateint data takeover discussion for 1.x, I'd postpone this. It may be too restrictive but that shouldn't create a risk. 

@MartinKasp & @PeterKranich :  Is that ok for you?

**Comment by PeterKranich** [comment]
@AnnaFeiler: this is ok for me. This is not only true for the patient but also for the Location Context and maybe for the WorkflowContext relating to the Encounter (#331).

**Comment by riechkathrin** [comment]
Isn't this solved now @PeterKranich?

**Comment by AnnaFeiler** [comment]
Already done
