### ISSUE TITLE
References not properly rendered in section titles when converted to HTML

### ISSUE THREAD

**Issue by ToddCooper** [IHE/sdpi-fhir#363]
## Section Number

Entire document

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue

Links do not properly resolve in section titles when converted from AsciiDoc to HTML.  For example, _**<<acronym_md_lan>>**_, is converted to _**<a href="#acronym_md_lan">MD LAN</a>**_.  This has been the source of numerous review comments to fix and the "fix" is either hard-wiring the text (e.g., "MD LAN") or defining a variable (e.g., {var_acronym_md_lan}, which does get properly expanded / replaced BUT then creates a unnecessarily duplicated approach for standard text substitutions that are NOT "variables" but static.  

## Proposed Change

Explore the conversion process from AsciiDoc to HTML to determine if the link can be omitted when it appears in a section title.

**Comment by AnnaFeiler** [comment]
Please double check,if that fixes the broken references in B.3.4.6.1 OBX-1 Set ID - OBX
