### ISSUE TITLE
Export of overflow and underflow values 

### ISSUE THREAD

**Issue by AnnaFeiler** [IHE/sdpi-fhir#382]
## Section Number

B.3.4.6.8 OBX-8 Abnormal Flags

## Priority

- *Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.*

## Issue

If we would allow metric values that are not valid or validated to be exported, we could provide overflow and underflow values. 

## Proposed Change

Discuss, if overflow and underflow need to be supported and update accordingly. Adapt R8017 as needed.

**Comment by PeterKranich** [comment]
@AnnaFeiler: this is fixed with #372. As of now, only valid and validated value shall be exported.

**Comment by AnnaFeiler** [comment]
@MartinKasp : I'm sorting through our remaining issues. Do we want to keep this or are we ok with exporting only valid values.

**Comment by MartinKasp** [comment]
We can close this issue an just go for valid values.
