### ISSUE TITLE
Replace IHE logo on title page 

### ISSUE THREAD

**Issue by MaryLJ** [IHE/sdpi-fhir#398]
## Section Number
Title page

## Priority
Low

## Issue
Replace IHE logo on title page 

## Proposed Change
Use the attached logo
![IHE_LOGO_for_tf-docs](https://user-images.githubusercontent.com/25642425/219494342-72257470-2cbf-4912-a4b2-342e1db71075.jpg)

**Comment by ToddCooper** [comment]
@d-gregorczyk  This is related to #401.  When you adjust the IHE and HL7 logos, can you substitute the IHE logo for this one?

**Comment by d-gregorczyk** [comment]
This is a very small JPG logo... don't we have an SVG? Would it be ok to carve out the IHE portion from the SVG logo we already have? Would be much more crispier and cleaner in the output document :-)

**Comment by d-gregorczyk** [comment]
Ok nevermind, the IHE logo in the SVG is just an embedded regular pixel picture...

**Comment by d-gregorczyk** [comment]
I just posted an update to #401 - please verify if this is okay.

**Comment by ToddCooper** [comment]
Closed with the merge of PR #401
