### ISSUE TITLE
Append TOI: Compression Option

### ISSUE THREAD

**Issue by d-gregorczyk** [IHE/sdpi-fhir#97]
See also: https://confluence.hl7.org/display/GP/Topic%3A+SDPi-P+Compression+Option

**Comment by ToddCooper** [comment]
Update related [sdpi-supplement-issues.adoc](https://github.com/IHE/sdpi-fhir/blob/master/SDPi_Supplement/asciidoc/sdpi-supplement-issues.adoc)  item when complete, indicating where the updates were made or the branche(s) that captured the updates, as well as moving from OPEN to CLOSED lists if appropriate.

**Comment by ToddCooper** [comment]
@d-gregorczyk --  Note:  This topic is still listed as OPEN in the [Topics of Interest](https://confluence.hl7.org/pages/viewpage.action?pageId=82912211#TopicsofInterest-TopicsontheTable) Table entry.  So it is listed in the OPEN list in the SDPi Supplement Issues page.  Yes?  No?

**Comment by ToddCooper** [comment]
From the SDPi 1.0 Workshop:  Mostly for Vol 2 Appendix A

**Comment by JavierEspina** [comment]
> From the SDPi 1.0 Workshop: _**Supporting HTTP compression is mandatory, everything (e.g. EXI) else is not. David will put in the MDPWS appendix and Todd will provide it in SDPi-P in transport agnostic language.**_

I did the "put in MDPWS appendix" part, which David is reviewing (see related PR). @ToddCooper, I'm not sure what this leaves "...in SDPI-P in transport agnostic language"

**Comment by JavierEspina** [comment]
We had some trouble understanding each other above... But the bottom line is that I think we're fine with the closure of this PR and related issue. We can do / trigger the clean-up of the TOI page, SmartSheet row and [sdpi-supplement-issues.adoc](https://github.com/IHE/sdpi-fhir/blob/master/SDPi_Supplement/asciidoc/sdpi-supplement-issues.adoc) this Friday at the SDPi call. And we could always open a new issue later IF any DEV Domain or PC reviewer requests for more "mandatoryness" than the current recommendations.

**Comment by ToddCooper** [comment]
I'll put it on the Friday agenda ...

~>Todd 탇

*Soli Deo gloria*

M:  +1 858.442.9200
S:  ToddCooperAFC
